USE [PcPartsManager]
-- dirty read
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM CPUs
WAITFOR DELAY '00:00:15'
SELECT * FROM CPUs
COMMIT TRAN
-- just a select
SELECT * FROM CPUs
-- how to solve dirty read:
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM CPUs
WAITFOR DELAY '00:00:15'
SELECT * FROM CPUs
COMMIT TRAN

--	non-repeatable reads
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM CPUs;
WAITFOR DELAY '00:00:15';
SELECT * FROM CPUs;
COMMIT TRAN
-- solving non-repetable reads
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM CPUs;
WAITFOR DELAY '00:00:15';
SELECT * FROM CPUs;
COMMIT TRAN

-- PHANTOM READS DOES NOT APPEA IN FIRST SELECT, BUT APPEARS IN SECOND
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM CPUs WHERE model='Intel Core i9-13900K special boost potion'
WAITFOR DELAY '00:00:15'
SELECT * FROM CPUs WHERE model='Intel Core i9-13900K special boost potion'
COMMIT TRAN
-- SOLVING PHANTOM READS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM CPUs WHERE model='Intel Core i9-13900K special boost potion'
WAITFOR DELAY '00:00:15'
SELECT * FROM CPUs WHERE model='Intel Core i9-13900K special boost potion'
COMMIT TRAN

-- deadlock
BEGIN TRAN
UPDATE Motherboards SET model='Asus DEADLOCK2' WHERE motherboardId=23084
WAITFOR DELAY '00:00:10'
UPDATE CPUs SET model='Intel DEADLOCK2' WHERE cpuId=23155
SELECT * FROM CPUs;
SELECT * FROM Motherboards;
COMMIT TRAN
-- fix
SET DEADLOCK_PRIORITY HIGH --/LOW
BEGIN TRAN
UPDATE Motherboards SET model='Asus DEADLOCK2' WHERE motherboardId=23084
WAITFOR DELAY '00:00:10'
UPDATE CPUs SET model='Intel DEADLOCK2' WHERE cpuId=23155
SELECT * FROM CPUs;
SELECT * FROM Motherboards;
COMMIT TRAN
-- complete fix // same order
SET DEADLOCK_PRIORITY HIGH --/LOW
BEGIN TRAN
UPDATE CPUs SET model='Intel DEADLOCK2' WHERE cpuId=23155
WAITFOR DELAY '00:00:10'
UPDATE Motherboards SET model='Asus DEADLOCK2' WHERE motherboardId=23084
SELECT * FROM CPUs;
SELECT * FROM Motherboards;
COMMIT TRAN