version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: simple_train_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: trenuri
      MYSQL_USER: badel
      MYSQL_PASSWORD: badel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: