// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChatProtocol_v3.proto
// Protobuf Java Version: 4.29.3

package chat.network.protobuffprotocol;

public final class ChatProtobufs {
  private ChatProtobufs() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ChatProtobufs.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_protocol_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_protocol_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_protocol_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_protocol_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_protocol_ChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_protocol_ChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_protocol_ChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_protocol_ChatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ChatProtocol_v3.proto\022\rchat.protocol\"\"" +
      "\n\004User\022\n\n\002id\030\001 \001(\t\022\016\n\006passwd\030\002 \001(\t\"=\n\007Me" +
      "ssage\022\022\n\nreceiverId\030\001 \001(\t\022\020\n\010senderId\030\002 " +
      "\001(\t\022\014\n\004text\030\003 \001(\t\"\351\001\n\013ChatRequest\022-\n\004typ" +
      "e\030\001 \001(\0162\037.chat.protocol.ChatRequest.Type" +
      "\022#\n\004user\030\002 \001(\0132\023.chat.protocol.UserH\000\022)\n" +
      "\007message\030\003 \001(\0132\026.chat.protocol.MessageH\000" +
      "\"P\n\004Type\022\n\n\006Unkown\020\000\022\t\n\005Login\020\001\022\n\n\006Logou" +
      "t\020\002\022\017\n\013SendMessage\020\003\022\024\n\020GetLoggedFriends" +
      "\020\004B\t\n\007payload\"\266\002\n\014ChatResponse\022.\n\004type\030\001" +
      " \001(\0162 .chat.protocol.ChatResponse.Type\022\r" +
      "\n\005error\030\002 \001(\t\022$\n\007friends\030\003 \003(\0132\023.chat.pr" +
      "otocol.User\022!\n\004user\030\004 \001(\0132\023.chat.protoco" +
      "l.User\022\'\n\007message\030\005 \001(\0132\026.chat.protocol." +
      "Message\"u\n\004Type\022\013\n\007Unknown\020\000\022\006\n\002Ok\020\001\022\t\n\005" +
      "Error\020\002\022\024\n\020GetLoggedFriends\020\003\022\022\n\016FriendL" +
      "oggedIn\020\004\022\023\n\017FriendLoggedOut\020\005\022\016\n\nNewMes" +
      "sage\020\006B1\n\036chat.network.protobuffprotocol" +
      "B\rChatProtobufsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chat_protocol_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_protocol_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_protocol_User_descriptor,
        new java.lang.String[] { "Id", "Passwd", });
    internal_static_chat_protocol_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chat_protocol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_protocol_Message_descriptor,
        new java.lang.String[] { "ReceiverId", "SenderId", "Text", });
    internal_static_chat_protocol_ChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chat_protocol_ChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_protocol_ChatRequest_descriptor,
        new java.lang.String[] { "Type", "User", "Message", "Payload", });
    internal_static_chat_protocol_ChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chat_protocol_ChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_protocol_ChatResponse_descriptor,
        new java.lang.String[] { "Type", "Error", "Friends", "User", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
