// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChatProtocol_v3.proto
// Protobuf Java Version: 4.29.3

package chat.network.protobuffprotocol;

public interface ChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.protocol.ChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
   * @return The type.
   */
  chat.network.protobuffprotocol.ChatRequest.Type getType();

  /**
   * <code>.chat.protocol.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.chat.protocol.User user = 2;</code>
   * @return The user.
   */
  chat.network.protobuffprotocol.User getUser();
  /**
   * <code>.chat.protocol.User user = 2;</code>
   */
  chat.network.protobuffprotocol.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.chat.protocol.Message message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.chat.protocol.Message message = 3;</code>
   * @return The message.
   */
  chat.network.protobuffprotocol.Message getMessage();
  /**
   * <code>.chat.protocol.Message message = 3;</code>
   */
  chat.network.protobuffprotocol.MessageOrBuilder getMessageOrBuilder();

  chat.network.protobuffprotocol.ChatRequest.PayloadCase getPayloadCase();
}
