// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChatProtocol_v3.proto
// Protobuf Java Version: 4.29.3

package chat.network.protobuffprotocol;

/**
 * Protobuf type {@code chat.protocol.ChatResponse}
 */
public final class ChatResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:chat.protocol.ChatResponse)
    ChatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ChatResponse.class.getName());
  }
  // Use ChatResponse.newBuilder() to construct.
  private ChatResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChatResponse() {
    type_ = 0;
    error_ = "";
    friends_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            chat.network.protobuffprotocol.ChatResponse.class, chat.network.protobuffprotocol.ChatResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code chat.protocol.ChatResponse.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>Ok = 1;</code>
     */
    Ok(1),
    /**
     * <code>Error = 2;</code>
     */
    Error(2),
    /**
     * <code>GetLoggedFriends = 3;</code>
     */
    GetLoggedFriends(3),
    /**
     * <code>FriendLoggedIn = 4;</code>
     */
    FriendLoggedIn(4),
    /**
     * <code>FriendLoggedOut = 5;</code>
     */
    FriendLoggedOut(5),
    /**
     * <code>NewMessage = 6;</code>
     */
    NewMessage(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Type.class.getName());
    }
    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>Ok = 1;</code>
     */
    public static final int Ok_VALUE = 1;
    /**
     * <code>Error = 2;</code>
     */
    public static final int Error_VALUE = 2;
    /**
     * <code>GetLoggedFriends = 3;</code>
     */
    public static final int GetLoggedFriends_VALUE = 3;
    /**
     * <code>FriendLoggedIn = 4;</code>
     */
    public static final int FriendLoggedIn_VALUE = 4;
    /**
     * <code>FriendLoggedOut = 5;</code>
     */
    public static final int FriendLoggedOut_VALUE = 5;
    /**
     * <code>NewMessage = 6;</code>
     */
    public static final int NewMessage_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return Ok;
        case 2: return Error;
        case 3: return GetLoggedFriends;
        case 4: return FriendLoggedIn;
        case 5: return FriendLoggedOut;
        case 6: return NewMessage;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return chat.network.protobuffprotocol.ChatResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:chat.protocol.ChatResponse.Type)
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.chat.protocol.ChatResponse.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.chat.protocol.ChatResponse.Type type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public chat.network.protobuffprotocol.ChatResponse.Type getType() {
    chat.network.protobuffprotocol.ChatResponse.Type result = chat.network.protobuffprotocol.ChatResponse.Type.forNumber(type_);
    return result == null ? chat.network.protobuffprotocol.ChatResponse.Type.UNRECOGNIZED : result;
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>string error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * One of the following will be filled in, depending on the type.
   * </pre>
   *
   * <code>string error = 2;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRIENDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<chat.network.protobuffprotocol.User> friends_;
  /**
   * <code>repeated .chat.protocol.User friends = 3;</code>
   */
  @java.lang.Override
  public java.util.List<chat.network.protobuffprotocol.User> getFriendsList() {
    return friends_;
  }
  /**
   * <code>repeated .chat.protocol.User friends = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends chat.network.protobuffprotocol.UserOrBuilder> 
      getFriendsOrBuilderList() {
    return friends_;
  }
  /**
   * <code>repeated .chat.protocol.User friends = 3;</code>
   */
  @java.lang.Override
  public int getFriendsCount() {
    return friends_.size();
  }
  /**
   * <code>repeated .chat.protocol.User friends = 3;</code>
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.User getFriends(int index) {
    return friends_.get(index);
  }
  /**
   * <code>repeated .chat.protocol.User friends = 3;</code>
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.UserOrBuilder getFriendsOrBuilder(
      int index) {
    return friends_.get(index);
  }

  public static final int USER_FIELD_NUMBER = 4;
  private chat.network.protobuffprotocol.User user_;
  /**
   * <code>.chat.protocol.User user = 4;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.chat.protocol.User user = 4;</code>
   * @return The user.
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.User getUser() {
    return user_ == null ? chat.network.protobuffprotocol.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.chat.protocol.User user = 4;</code>
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.UserOrBuilder getUserOrBuilder() {
    return user_ == null ? chat.network.protobuffprotocol.User.getDefaultInstance() : user_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 5;
  private chat.network.protobuffprotocol.Message message_;
  /**
   * <code>.chat.protocol.Message message = 5;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.chat.protocol.Message message = 5;</code>
   * @return The message.
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.Message getMessage() {
    return message_ == null ? chat.network.protobuffprotocol.Message.getDefaultInstance() : message_;
  }
  /**
   * <code>.chat.protocol.Message message = 5;</code>
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.MessageOrBuilder getMessageOrBuilder() {
    return message_ == null ? chat.network.protobuffprotocol.Message.getDefaultInstance() : message_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != chat.network.protobuffprotocol.ChatResponse.Type.Unknown.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, error_);
    }
    for (int i = 0; i < friends_.size(); i++) {
      output.writeMessage(3, friends_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getUser());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getMessage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != chat.network.protobuffprotocol.ChatResponse.Type.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, error_);
    }
    for (int i = 0; i < friends_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, friends_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUser());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getMessage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof chat.network.protobuffprotocol.ChatResponse)) {
      return super.equals(obj);
    }
    chat.network.protobuffprotocol.ChatResponse other = (chat.network.protobuffprotocol.ChatResponse) obj;

    if (type_ != other.type_) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getFriendsList()
        .equals(other.getFriendsList())) return false;
    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (getFriendsCount() > 0) {
      hash = (37 * hash) + FRIENDS_FIELD_NUMBER;
      hash = (53 * hash) + getFriendsList().hashCode();
    }
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static chat.network.protobuffprotocol.ChatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static chat.network.protobuffprotocol.ChatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static chat.network.protobuffprotocol.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(chat.network.protobuffprotocol.ChatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chat.protocol.ChatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chat.protocol.ChatResponse)
      chat.network.protobuffprotocol.ChatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              chat.network.protobuffprotocol.ChatResponse.class, chat.network.protobuffprotocol.ChatResponse.Builder.class);
    }

    // Construct using chat.network.protobuffprotocol.ChatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getFriendsFieldBuilder();
        getUserFieldBuilder();
        getMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      error_ = "";
      if (friendsBuilder_ == null) {
        friends_ = java.util.Collections.emptyList();
      } else {
        friends_ = null;
        friendsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatResponse_descriptor;
    }

    @java.lang.Override
    public chat.network.protobuffprotocol.ChatResponse getDefaultInstanceForType() {
      return chat.network.protobuffprotocol.ChatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public chat.network.protobuffprotocol.ChatResponse build() {
      chat.network.protobuffprotocol.ChatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public chat.network.protobuffprotocol.ChatResponse buildPartial() {
      chat.network.protobuffprotocol.ChatResponse result = new chat.network.protobuffprotocol.ChatResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(chat.network.protobuffprotocol.ChatResponse result) {
      if (friendsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          friends_ = java.util.Collections.unmodifiableList(friends_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.friends_ = friends_;
      } else {
        result.friends_ = friendsBuilder_.build();
      }
    }

    private void buildPartial0(chat.network.protobuffprotocol.ChatResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.error_ = error_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.user_ = userBuilder_ == null
            ? user_
            : userBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.message_ = messageBuilder_ == null
            ? message_
            : messageBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof chat.network.protobuffprotocol.ChatResponse) {
        return mergeFrom((chat.network.protobuffprotocol.ChatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(chat.network.protobuffprotocol.ChatResponse other) {
      if (other == chat.network.protobuffprotocol.ChatResponse.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (friendsBuilder_ == null) {
        if (!other.friends_.isEmpty()) {
          if (friends_.isEmpty()) {
            friends_ = other.friends_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFriendsIsMutable();
            friends_.addAll(other.friends_);
          }
          onChanged();
        }
      } else {
        if (!other.friends_.isEmpty()) {
          if (friendsBuilder_.isEmpty()) {
            friendsBuilder_.dispose();
            friendsBuilder_ = null;
            friends_ = other.friends_;
            bitField0_ = (bitField0_ & ~0x00000004);
            friendsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getFriendsFieldBuilder() : null;
          } else {
            friendsBuilder_.addAllMessages(other.friends_);
          }
        }
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              chat.network.protobuffprotocol.User m =
                  input.readMessage(
                      chat.network.protobuffprotocol.User.parser(),
                      extensionRegistry);
              if (friendsBuilder_ == null) {
                ensureFriendsIsMutable();
                friends_.add(m);
              } else {
                friendsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatResponse.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatResponse.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatResponse.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public chat.network.protobuffprotocol.ChatResponse.Type getType() {
      chat.network.protobuffprotocol.ChatResponse.Type result = chat.network.protobuffprotocol.ChatResponse.Type.forNumber(type_);
      return result == null ? chat.network.protobuffprotocol.ChatResponse.Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatResponse.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(chat.network.protobuffprotocol.ChatResponse.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatResponse.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>string error = 2;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>string error = 2;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>string error = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * One of the following will be filled in, depending on the type.
     * </pre>
     *
     * <code>string error = 2;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<chat.network.protobuffprotocol.User> friends_ =
      java.util.Collections.emptyList();
    private void ensureFriendsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        friends_ = new java.util.ArrayList<chat.network.protobuffprotocol.User>(friends_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder> friendsBuilder_;

    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public java.util.List<chat.network.protobuffprotocol.User> getFriendsList() {
      if (friendsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(friends_);
      } else {
        return friendsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public int getFriendsCount() {
      if (friendsBuilder_ == null) {
        return friends_.size();
      } else {
        return friendsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public chat.network.protobuffprotocol.User getFriends(int index) {
      if (friendsBuilder_ == null) {
        return friends_.get(index);
      } else {
        return friendsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder setFriends(
        int index, chat.network.protobuffprotocol.User value) {
      if (friendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendsIsMutable();
        friends_.set(index, value);
        onChanged();
      } else {
        friendsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder setFriends(
        int index, chat.network.protobuffprotocol.User.Builder builderForValue) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.set(index, builderForValue.build());
        onChanged();
      } else {
        friendsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder addFriends(chat.network.protobuffprotocol.User value) {
      if (friendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendsIsMutable();
        friends_.add(value);
        onChanged();
      } else {
        friendsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder addFriends(
        int index, chat.network.protobuffprotocol.User value) {
      if (friendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFriendsIsMutable();
        friends_.add(index, value);
        onChanged();
      } else {
        friendsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder addFriends(
        chat.network.protobuffprotocol.User.Builder builderForValue) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.add(builderForValue.build());
        onChanged();
      } else {
        friendsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder addFriends(
        int index, chat.network.protobuffprotocol.User.Builder builderForValue) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.add(index, builderForValue.build());
        onChanged();
      } else {
        friendsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder addAllFriends(
        java.lang.Iterable<? extends chat.network.protobuffprotocol.User> values) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, friends_);
        onChanged();
      } else {
        friendsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder clearFriends() {
      if (friendsBuilder_ == null) {
        friends_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        friendsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public Builder removeFriends(int index) {
      if (friendsBuilder_ == null) {
        ensureFriendsIsMutable();
        friends_.remove(index);
        onChanged();
      } else {
        friendsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public chat.network.protobuffprotocol.User.Builder getFriendsBuilder(
        int index) {
      return getFriendsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public chat.network.protobuffprotocol.UserOrBuilder getFriendsOrBuilder(
        int index) {
      if (friendsBuilder_ == null) {
        return friends_.get(index);  } else {
        return friendsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public java.util.List<? extends chat.network.protobuffprotocol.UserOrBuilder> 
         getFriendsOrBuilderList() {
      if (friendsBuilder_ != null) {
        return friendsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(friends_);
      }
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public chat.network.protobuffprotocol.User.Builder addFriendsBuilder() {
      return getFriendsFieldBuilder().addBuilder(
          chat.network.protobuffprotocol.User.getDefaultInstance());
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public chat.network.protobuffprotocol.User.Builder addFriendsBuilder(
        int index) {
      return getFriendsFieldBuilder().addBuilder(
          index, chat.network.protobuffprotocol.User.getDefaultInstance());
    }
    /**
     * <code>repeated .chat.protocol.User friends = 3;</code>
     */
    public java.util.List<chat.network.protobuffprotocol.User.Builder> 
         getFriendsBuilderList() {
      return getFriendsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder> 
        getFriendsFieldBuilder() {
      if (friendsBuilder_ == null) {
        friendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder>(
                friends_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        friends_ = null;
      }
      return friendsBuilder_;
    }

    private chat.network.protobuffprotocol.User user_;
    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder> userBuilder_;
    /**
     * <code>.chat.protocol.User user = 4;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     * @return The user.
     */
    public chat.network.protobuffprotocol.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? chat.network.protobuffprotocol.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     */
    public Builder setUser(chat.network.protobuffprotocol.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
      } else {
        userBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     */
    public Builder setUser(
        chat.network.protobuffprotocol.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     */
    public Builder mergeUser(chat.network.protobuffprotocol.User value) {
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          user_ != null &&
          user_ != chat.network.protobuffprotocol.User.getDefaultInstance()) {
          getUserBuilder().mergeFrom(value);
        } else {
          user_ = value;
        }
      } else {
        userBuilder_.mergeFrom(value);
      }
      if (user_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     */
    public Builder clearUser() {
      bitField0_ = (bitField0_ & ~0x00000008);
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     */
    public chat.network.protobuffprotocol.User.Builder getUserBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     */
    public chat.network.protobuffprotocol.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            chat.network.protobuffprotocol.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.chat.protocol.User user = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private chat.network.protobuffprotocol.Message message_;
    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.Message, chat.network.protobuffprotocol.Message.Builder, chat.network.protobuffprotocol.MessageOrBuilder> messageBuilder_;
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     * @return The message.
     */
    public chat.network.protobuffprotocol.Message getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? chat.network.protobuffprotocol.Message.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     */
    public Builder setMessage(chat.network.protobuffprotocol.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
      } else {
        messageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     */
    public Builder setMessage(
        chat.network.protobuffprotocol.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     */
    public Builder mergeMessage(chat.network.protobuffprotocol.Message value) {
      if (messageBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          message_ != null &&
          message_ != chat.network.protobuffprotocol.Message.getDefaultInstance()) {
          getMessageBuilder().mergeFrom(value);
        } else {
          message_ = value;
        }
      } else {
        messageBuilder_.mergeFrom(value);
      }
      if (message_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000010);
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     */
    public chat.network.protobuffprotocol.Message.Builder getMessageBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     */
    public chat.network.protobuffprotocol.MessageOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            chat.network.protobuffprotocol.Message.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.chat.protocol.Message message = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.Message, chat.network.protobuffprotocol.Message.Builder, chat.network.protobuffprotocol.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            chat.network.protobuffprotocol.Message, chat.network.protobuffprotocol.Message.Builder, chat.network.protobuffprotocol.MessageOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:chat.protocol.ChatResponse)
  }

  // @@protoc_insertion_point(class_scope:chat.protocol.ChatResponse)
  private static final chat.network.protobuffprotocol.ChatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new chat.network.protobuffprotocol.ChatResponse();
  }

  public static chat.network.protobuffprotocol.ChatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatResponse>
      PARSER = new com.google.protobuf.AbstractParser<ChatResponse>() {
    @java.lang.Override
    public ChatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public chat.network.protobuffprotocol.ChatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

