// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChatProtocol_v3.proto
// Protobuf Java Version: 4.29.3

package chat.network.protobuffprotocol;

/**
 * Protobuf type {@code chat.protocol.ChatRequest}
 */
public final class ChatRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:chat.protocol.ChatRequest)
    ChatRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ChatRequest.class.getName());
  }
  // Use ChatRequest.newBuilder() to construct.
  private ChatRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChatRequest() {
    type_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            chat.network.protobuffprotocol.ChatRequest.class, chat.network.protobuffprotocol.ChatRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code chat.protocol.ChatRequest.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unkown = 0;</code>
     */
    Unkown(0),
    /**
     * <code>Login = 1;</code>
     */
    Login(1),
    /**
     * <code>Logout = 2;</code>
     */
    Logout(2),
    /**
     * <code>SendMessage = 3;</code>
     */
    SendMessage(3),
    /**
     * <code>GetLoggedFriends = 4;</code>
     */
    GetLoggedFriends(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Type.class.getName());
    }
    /**
     * <code>Unkown = 0;</code>
     */
    public static final int Unkown_VALUE = 0;
    /**
     * <code>Login = 1;</code>
     */
    public static final int Login_VALUE = 1;
    /**
     * <code>Logout = 2;</code>
     */
    public static final int Logout_VALUE = 2;
    /**
     * <code>SendMessage = 3;</code>
     */
    public static final int SendMessage_VALUE = 3;
    /**
     * <code>GetLoggedFriends = 4;</code>
     */
    public static final int GetLoggedFriends_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return Unkown;
        case 1: return Login;
        case 2: return Logout;
        case 3: return SendMessage;
        case 4: return GetLoggedFriends;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return chat.network.protobuffprotocol.ChatRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:chat.protocol.ChatRequest.Type)
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    USER(2),
    MESSAGE(3),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return USER;
        case 3: return MESSAGE;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Identifies which request is filled in.
   * </pre>
   *
   * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public chat.network.protobuffprotocol.ChatRequest.Type getType() {
    chat.network.protobuffprotocol.ChatRequest.Type result = chat.network.protobuffprotocol.ChatRequest.Type.forNumber(type_);
    return result == null ? chat.network.protobuffprotocol.ChatRequest.Type.UNRECOGNIZED : result;
  }

  public static final int USER_FIELD_NUMBER = 2;
  /**
   * <code>.chat.protocol.User user = 2;</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.chat.protocol.User user = 2;</code>
   * @return The user.
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.User getUser() {
    if (payloadCase_ == 2) {
       return (chat.network.protobuffprotocol.User) payload_;
    }
    return chat.network.protobuffprotocol.User.getDefaultInstance();
  }
  /**
   * <code>.chat.protocol.User user = 2;</code>
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.UserOrBuilder getUserOrBuilder() {
    if (payloadCase_ == 2) {
       return (chat.network.protobuffprotocol.User) payload_;
    }
    return chat.network.protobuffprotocol.User.getDefaultInstance();
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  /**
   * <code>.chat.protocol.Message message = 3;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.chat.protocol.Message message = 3;</code>
   * @return The message.
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.Message getMessage() {
    if (payloadCase_ == 3) {
       return (chat.network.protobuffprotocol.Message) payload_;
    }
    return chat.network.protobuffprotocol.Message.getDefaultInstance();
  }
  /**
   * <code>.chat.protocol.Message message = 3;</code>
   */
  @java.lang.Override
  public chat.network.protobuffprotocol.MessageOrBuilder getMessageOrBuilder() {
    if (payloadCase_ == 3) {
       return (chat.network.protobuffprotocol.Message) payload_;
    }
    return chat.network.protobuffprotocol.Message.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != chat.network.protobuffprotocol.ChatRequest.Type.Unkown.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (chat.network.protobuffprotocol.User) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (chat.network.protobuffprotocol.Message) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != chat.network.protobuffprotocol.ChatRequest.Type.Unkown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (chat.network.protobuffprotocol.User) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (chat.network.protobuffprotocol.Message) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof chat.network.protobuffprotocol.ChatRequest)) {
      return super.equals(obj);
    }
    chat.network.protobuffprotocol.ChatRequest other = (chat.network.protobuffprotocol.ChatRequest) obj;

    if (type_ != other.type_) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 2:
        if (!getUser()
            .equals(other.getUser())) return false;
        break;
      case 3:
        if (!getMessage()
            .equals(other.getMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (payloadCase_) {
      case 2:
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
        break;
      case 3:
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static chat.network.protobuffprotocol.ChatRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static chat.network.protobuffprotocol.ChatRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static chat.network.protobuffprotocol.ChatRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(chat.network.protobuffprotocol.ChatRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chat.protocol.ChatRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chat.protocol.ChatRequest)
      chat.network.protobuffprotocol.ChatRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              chat.network.protobuffprotocol.ChatRequest.class, chat.network.protobuffprotocol.ChatRequest.Builder.class);
    }

    // Construct using chat.network.protobuffprotocol.ChatRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      if (userBuilder_ != null) {
        userBuilder_.clear();
      }
      if (messageBuilder_ != null) {
        messageBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return chat.network.protobuffprotocol.ChatProtobufs.internal_static_chat_protocol_ChatRequest_descriptor;
    }

    @java.lang.Override
    public chat.network.protobuffprotocol.ChatRequest getDefaultInstanceForType() {
      return chat.network.protobuffprotocol.ChatRequest.getDefaultInstance();
    }

    @java.lang.Override
    public chat.network.protobuffprotocol.ChatRequest build() {
      chat.network.protobuffprotocol.ChatRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public chat.network.protobuffprotocol.ChatRequest buildPartial() {
      chat.network.protobuffprotocol.ChatRequest result = new chat.network.protobuffprotocol.ChatRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(chat.network.protobuffprotocol.ChatRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
    }

    private void buildPartialOneofs(chat.network.protobuffprotocol.ChatRequest result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 2 &&
          userBuilder_ != null) {
        result.payload_ = userBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          messageBuilder_ != null) {
        result.payload_ = messageBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof chat.network.protobuffprotocol.ChatRequest) {
        return mergeFrom((chat.network.protobuffprotocol.ChatRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(chat.network.protobuffprotocol.ChatRequest other) {
      if (other == chat.network.protobuffprotocol.ChatRequest.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getPayloadCase()) {
        case USER: {
          mergeUser(other.getUser());
          break;
        }
        case MESSAGE: {
          mergeMessage(other.getMessage());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public chat.network.protobuffprotocol.ChatRequest.Type getType() {
      chat.network.protobuffprotocol.ChatRequest.Type result = chat.network.protobuffprotocol.ChatRequest.Type.forNumber(type_);
      return result == null ? chat.network.protobuffprotocol.ChatRequest.Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(chat.network.protobuffprotocol.ChatRequest.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies which request is filled in.
     * </pre>
     *
     * <code>.chat.protocol.ChatRequest.Type type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder> userBuilder_;
    /**
     * <code>.chat.protocol.User user = 2;</code>
     * @return Whether the user field is set.
     */
    @java.lang.Override
    public boolean hasUser() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     * @return The user.
     */
    @java.lang.Override
    public chat.network.protobuffprotocol.User getUser() {
      if (userBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (chat.network.protobuffprotocol.User) payload_;
        }
        return chat.network.protobuffprotocol.User.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return userBuilder_.getMessage();
        }
        return chat.network.protobuffprotocol.User.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     */
    public Builder setUser(chat.network.protobuffprotocol.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     */
    public Builder setUser(
        chat.network.protobuffprotocol.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     */
    public Builder mergeUser(chat.network.protobuffprotocol.User value) {
      if (userBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != chat.network.protobuffprotocol.User.getDefaultInstance()) {
          payload_ = chat.network.protobuffprotocol.User.newBuilder((chat.network.protobuffprotocol.User) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          userBuilder_.mergeFrom(value);
        } else {
          userBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        userBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     */
    public chat.network.protobuffprotocol.User.Builder getUserBuilder() {
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     */
    @java.lang.Override
    public chat.network.protobuffprotocol.UserOrBuilder getUserOrBuilder() {
      if ((payloadCase_ == 2) && (userBuilder_ != null)) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (chat.network.protobuffprotocol.User) payload_;
        }
        return chat.network.protobuffprotocol.User.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.protocol.User user = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = chat.network.protobuffprotocol.User.getDefaultInstance();
        }
        userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            chat.network.protobuffprotocol.User, chat.network.protobuffprotocol.User.Builder, chat.network.protobuffprotocol.UserOrBuilder>(
                (chat.network.protobuffprotocol.User) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return userBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.Message, chat.network.protobuffprotocol.Message.Builder, chat.network.protobuffprotocol.MessageOrBuilder> messageBuilder_;
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public chat.network.protobuffprotocol.Message getMessage() {
      if (messageBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (chat.network.protobuffprotocol.Message) payload_;
        }
        return chat.network.protobuffprotocol.Message.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return messageBuilder_.getMessage();
        }
        return chat.network.protobuffprotocol.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     */
    public Builder setMessage(chat.network.protobuffprotocol.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     */
    public Builder setMessage(
        chat.network.protobuffprotocol.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     */
    public Builder mergeMessage(chat.network.protobuffprotocol.Message value) {
      if (messageBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != chat.network.protobuffprotocol.Message.getDefaultInstance()) {
          payload_ = chat.network.protobuffprotocol.Message.newBuilder((chat.network.protobuffprotocol.Message) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          messageBuilder_.mergeFrom(value);
        } else {
          messageBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     */
    public chat.network.protobuffprotocol.Message.Builder getMessageBuilder() {
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     */
    @java.lang.Override
    public chat.network.protobuffprotocol.MessageOrBuilder getMessageOrBuilder() {
      if ((payloadCase_ == 3) && (messageBuilder_ != null)) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (chat.network.protobuffprotocol.Message) payload_;
        }
        return chat.network.protobuffprotocol.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.protocol.Message message = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        chat.network.protobuffprotocol.Message, chat.network.protobuffprotocol.Message.Builder, chat.network.protobuffprotocol.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = chat.network.protobuffprotocol.Message.getDefaultInstance();
        }
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            chat.network.protobuffprotocol.Message, chat.network.protobuffprotocol.Message.Builder, chat.network.protobuffprotocol.MessageOrBuilder>(
                (chat.network.protobuffprotocol.Message) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return messageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:chat.protocol.ChatRequest)
  }

  // @@protoc_insertion_point(class_scope:chat.protocol.ChatRequest)
  private static final chat.network.protobuffprotocol.ChatRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new chat.network.protobuffprotocol.ChatRequest();
  }

  public static chat.network.protobuffprotocol.ChatRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChatRequest>() {
    @java.lang.Override
    public ChatRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public chat.network.protobuffprotocol.ChatRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

