// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChatProtocol_v3.proto
// Protobuf Java Version: 4.29.3

package chat.network.protobuffprotocol;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.protocol.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string receiverId = 1;</code>
   * @return The receiverId.
   */
  java.lang.String getReceiverId();
  /**
   * <code>string receiverId = 1;</code>
   * @return The bytes for receiverId.
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>string senderId = 2;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string senderId = 2;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
