// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ChatProtocol_v3.proto
// Protobuf Java Version: 4.29.3

package chat.network.protobuffprotocol;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.protocol.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string passwd = 2;</code>
   * @return The passwd.
   */
  java.lang.String getPasswd();
  /**
   * <code>string passwd = 2;</code>
   * @return The bytes for passwd.
   */
  com.google.protobuf.ByteString
      getPasswdBytes();
}
