(defun teste ()
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 1) 1)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 2) 2)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 3) 2)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 4) 2)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 5) 2)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 6) 1)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 7) 1)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 8) 1)
    (= (numar_atomi_nivel_k '(a (b (d (e (f)))) (c (g (h (i (j (k (l)))))))) 9) 0)

    (= (numar_atomi_nivel_k '(a (b (f)) (c (g (h)) (i)) (d (e))) 1) 1)
    (= (numar_atomi_nivel_k '(a (b (f)) (c (g (h)) (i)) (d (e))) 2) 3)
    (= (numar_atomi_nivel_k '(a (b (f)) (c (g (h)) (i)) (d (e))) 3) 4)
    (= (numar_atomi_nivel_k '(a (b (f)) (c (g (h)) (i)) (d (e))) 4) 1)
    (= (numar_atomi_nivel_k '(a (b (f)) (c (g (h)) (i)) (d (e))) 5) 0)
)