// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto_buffs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from proto_buffs.proto</summary>
public static partial class ProtoBuffsReflection {

  #region Descriptor
  /// <summary>File descriptor for proto_buffs.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtoBuffsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFwcm90b19idWZmcy5wcm90byIlCglBZ2VuY3lEVE8SCgoCaWQYASABKAUS",
          "DAoEbmFtZRgCIAEoCSJlCgtFbXBsb3llZURUTxIKCgJpZBgBIAEoBRIQCgh1",
          "c2VybmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCRIRCglhZ2VuY3lfaWQY",
          "BCABKAUSEwoLYWdlbmN5X25hbWUYBSABKAkigwEKDEV4Y3Vyc2lvbkRUTxIK",
          "CgJpZBgBIAEoBRISCgphdHRyYWN0aW9uGAIgASgJEhYKDnRyYW5zcG9ydF9m",
          "aXJtGAMgASgJEhAKCG5vX3NlYXRzGAQgASgFEg0KBXByaWNlGAUgASgFEhoK",
          "EmJvYXJkaW5nX2RhdGVfdGltZRgGIAEoCSL/AQoOUmVzZXJ2YXRpb25EVE8S",
          "CgoCaWQYASABKAUSEwoLY2xpZW50X25hbWUYAiABKAkSFAoMcGhvbmVfbnVt",
          "YmVyGAMgASgJEhcKD25vX2Jvb2tlZF9zZWF0cxgEIAEoBRITCgtleGN1cnNp",
          "ZV9pZBgFIAEoBRISCgphdHRyYWN0aW9uGAYgASgJEhYKDnRyYW5zcG9ydF9m",
          "aXJtGAcgASgJEhAKCG5vX3NlYXRzGAggASgFEg0KBXByaWNlGAkgASgFEhoK",
          "EmJvYXJkaW5nX2RhdGVfdGltZRgKIAEoCRIRCglhZ2VuY3lfaWQYCyABKAUS",
          "DAoEbmFtZRgMIAEoCSLxAQoHUmVxdWVzdBIaCgR0eXBlGAEgASgOMgwuUmVx",
          "dWVzdFR5cGUSIgoMZW1wbG95ZWVfZHRvGAIgASgLMgwuRW1wbG95ZWVEVE8S",
          "HgoKYWdlbmN5X2R0bxgDIAEoCzIKLkFnZW5jeURUTxIoCg9yZXNlcnZhdGlv",
          "bl9kdG8YBCABKAsyDy5SZXNlcnZhdGlvbkRUTxIkCg1leGN1cnNpb25fZHRv",
          "GAUgASgLMg0uRXhjdXJzaW9uRFRPEhIKCmF0dHJhY3Rpb24YBiABKAkSEQoJ",
          "ZnJvbV9kYXRlGAcgASgJEg8KB3RvX2RhdGUYCCABKAkizgEKCFJlc3BvbnNl",
          "EhsKBHR5cGUYASABKA4yDS5SZXNwb25zZVR5cGUSIgoMZW1wbG95ZWVfZHRv",
          "GAIgASgLMgwuRW1wbG95ZWVEVE8SFQoNZXJyb3JfbWVzc2FnZRgDIAEoCRIk",
          "Cg1leGN1cnNpb25fZHRvGAQgAygLMg0uRXhjdXJzaW9uRFRPEigKD3Jlc2Vy",
          "dmF0aW9uX2R0bxgFIAMoCzIPLlJlc2VydmF0aW9uRFRPEhoKEm5vX3JlbWFp",
          "bmluZ19zZWF0cxgGIAEoBSreAQoLUmVxdWVzdFR5cGUSDQoJUkVRX0xPR0lO",
          "EAASDgoKUkVRX0xPR09VVBABEhoKFlJFUV9HRVRfQUxMX0VYQ1VSU0lPTlMQ",
          "AhImCiJSRVFfR0VUX0FMTF9SRVNFUlZBVElPTlNfT0ZfQUdFTkNZEAMSHgoa",
          "UkVRX0dFVF9OT19SRU1BSU5JTkdfU0VBVFMQBBIzCi9SRVFfR0VUX0FMTF9F",
          "WENVUlNJT05TX1dJVEhfREVTVElOQVRJT05fQkVUV0VFThAFEhcKE1JFUV9B",
          "RERfUkVTRVJWQVRJT04QBiqBAQoMUmVzcG9uc2VUeXBlEg4KClJFU1BfTE9H",
          "SU4QABIPCgtSRVNQX0xPR09VVBABEgsKB1JFU1BfT0sQAhIOCgpSRVNQX0VS",
          "Uk9SEAMSGQoVUkVTUF9CUk9BRENBU1RfVVBEQVRFEAQSGAoUUkVTUF9BRERf",
          "UkVTRVJWQVRJT04QBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::RequestType), typeof(global::ResponseType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AgencyDTO), global::AgencyDTO.Parser, new[]{ "Id", "Name" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EmployeeDTO), global::EmployeeDTO.Parser, new[]{ "Id", "Username", "Password", "AgencyId", "AgencyName" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ExcursionDTO), global::ExcursionDTO.Parser, new[]{ "Id", "Attraction", "TransportFirm", "NoSeats", "Price", "BoardingDateTime" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ReservationDTO), global::ReservationDTO.Parser, new[]{ "Id", "ClientName", "PhoneNumber", "NoBookedSeats", "ExcursieId", "Attraction", "TransportFirm", "NoSeats", "Price", "BoardingDateTime", "AgencyId", "Name" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Type", "EmployeeDto", "AgencyDto", "ReservationDto", "ExcursionDto", "Attraction", "FromDate", "ToDate" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Type", "EmployeeDto", "ErrorMessage", "ExcursionDto", "ReservationDto", "NoRemainingSeats" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum RequestType {
  [pbr::OriginalName("REQ_LOGIN")] ReqLogin = 0,
  [pbr::OriginalName("REQ_LOGOUT")] ReqLogout = 1,
  [pbr::OriginalName("REQ_GET_ALL_EXCURSIONS")] ReqGetAllExcursions = 2,
  [pbr::OriginalName("REQ_GET_ALL_RESERVATIONS_OF_AGENCY")] ReqGetAllReservationsOfAgency = 3,
  [pbr::OriginalName("REQ_GET_NO_REMAINING_SEATS")] ReqGetNoRemainingSeats = 4,
  [pbr::OriginalName("REQ_GET_ALL_EXCURSIONS_WITH_DESTINATION_BETWEEN")] ReqGetAllExcursionsWithDestinationBetween = 5,
  [pbr::OriginalName("REQ_ADD_RESERVATION")] ReqAddReservation = 6,
}

public enum ResponseType {
  [pbr::OriginalName("RESP_LOGIN")] RespLogin = 0,
  [pbr::OriginalName("RESP_LOGOUT")] RespLogout = 1,
  [pbr::OriginalName("RESP_OK")] RespOk = 2,
  [pbr::OriginalName("RESP_ERROR")] RespError = 3,
  [pbr::OriginalName("RESP_BROADCAST_UPDATE")] RespBroadcastUpdate = 4,
  [pbr::OriginalName("RESP_ADD_RESERVATION")] RespAddReservation = 5,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AgencyDTO : pb::IMessage<AgencyDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AgencyDTO> _parser = new pb::MessageParser<AgencyDTO>(() => new AgencyDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AgencyDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoBuffsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AgencyDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AgencyDTO(AgencyDTO other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AgencyDTO Clone() {
    return new AgencyDTO(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AgencyDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AgencyDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AgencyDTO other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EmployeeDTO : pb::IMessage<EmployeeDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EmployeeDTO> _parser = new pb::MessageParser<EmployeeDTO>(() => new EmployeeDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EmployeeDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoBuffsReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EmployeeDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EmployeeDTO(EmployeeDTO other) : this() {
    id_ = other.id_;
    username_ = other.username_;
    password_ = other.password_;
    agencyId_ = other.agencyId_;
    agencyName_ = other.agencyName_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EmployeeDTO Clone() {
    return new EmployeeDTO(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 2;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 3;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "agency_id" field.</summary>
  public const int AgencyIdFieldNumber = 4;
  private int agencyId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AgencyId {
    get { return agencyId_; }
    set {
      agencyId_ = value;
    }
  }

  /// <summary>Field number for the "agency_name" field.</summary>
  public const int AgencyNameFieldNumber = 5;
  private string agencyName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AgencyName {
    get { return agencyName_; }
    set {
      agencyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EmployeeDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EmployeeDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Username != other.Username) return false;
    if (Password != other.Password) return false;
    if (AgencyId != other.AgencyId) return false;
    if (AgencyName != other.AgencyName) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (AgencyId != 0) hash ^= AgencyId.GetHashCode();
    if (AgencyName.Length != 0) hash ^= AgencyName.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (AgencyId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(AgencyId);
    }
    if (AgencyName.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AgencyName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Username.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Password);
    }
    if (AgencyId != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(AgencyId);
    }
    if (AgencyName.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AgencyName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (AgencyId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AgencyId);
    }
    if (AgencyName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AgencyName);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EmployeeDTO other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    if (other.AgencyId != 0) {
      AgencyId = other.AgencyId;
    }
    if (other.AgencyName.Length != 0) {
      AgencyName = other.AgencyName;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
        case 32: {
          AgencyId = input.ReadInt32();
          break;
        }
        case 42: {
          AgencyName = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Username = input.ReadString();
          break;
        }
        case 26: {
          Password = input.ReadString();
          break;
        }
        case 32: {
          AgencyId = input.ReadInt32();
          break;
        }
        case 42: {
          AgencyName = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ExcursionDTO : pb::IMessage<ExcursionDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ExcursionDTO> _parser = new pb::MessageParser<ExcursionDTO>(() => new ExcursionDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ExcursionDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoBuffsReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ExcursionDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ExcursionDTO(ExcursionDTO other) : this() {
    id_ = other.id_;
    attraction_ = other.attraction_;
    transportFirm_ = other.transportFirm_;
    noSeats_ = other.noSeats_;
    price_ = other.price_;
    boardingDateTime_ = other.boardingDateTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ExcursionDTO Clone() {
    return new ExcursionDTO(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "attraction" field.</summary>
  public const int AttractionFieldNumber = 2;
  private string attraction_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Attraction {
    get { return attraction_; }
    set {
      attraction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "transport_firm" field.</summary>
  public const int TransportFirmFieldNumber = 3;
  private string transportFirm_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TransportFirm {
    get { return transportFirm_; }
    set {
      transportFirm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "no_seats" field.</summary>
  public const int NoSeatsFieldNumber = 4;
  private int noSeats_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NoSeats {
    get { return noSeats_; }
    set {
      noSeats_ = value;
    }
  }

  /// <summary>Field number for the "price" field.</summary>
  public const int PriceFieldNumber = 5;
  private int price_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Price {
    get { return price_; }
    set {
      price_ = value;
    }
  }

  /// <summary>Field number for the "boarding_date_time" field.</summary>
  public const int BoardingDateTimeFieldNumber = 6;
  private string boardingDateTime_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BoardingDateTime {
    get { return boardingDateTime_; }
    set {
      boardingDateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ExcursionDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ExcursionDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Attraction != other.Attraction) return false;
    if (TransportFirm != other.TransportFirm) return false;
    if (NoSeats != other.NoSeats) return false;
    if (Price != other.Price) return false;
    if (BoardingDateTime != other.BoardingDateTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Attraction.Length != 0) hash ^= Attraction.GetHashCode();
    if (TransportFirm.Length != 0) hash ^= TransportFirm.GetHashCode();
    if (NoSeats != 0) hash ^= NoSeats.GetHashCode();
    if (Price != 0) hash ^= Price.GetHashCode();
    if (BoardingDateTime.Length != 0) hash ^= BoardingDateTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Attraction.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Attraction);
    }
    if (TransportFirm.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(TransportFirm);
    }
    if (NoSeats != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NoSeats);
    }
    if (Price != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Price);
    }
    if (BoardingDateTime.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(BoardingDateTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Attraction.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Attraction);
    }
    if (TransportFirm.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(TransportFirm);
    }
    if (NoSeats != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NoSeats);
    }
    if (Price != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Price);
    }
    if (BoardingDateTime.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(BoardingDateTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Attraction.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Attraction);
    }
    if (TransportFirm.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TransportFirm);
    }
    if (NoSeats != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoSeats);
    }
    if (Price != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
    }
    if (BoardingDateTime.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BoardingDateTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ExcursionDTO other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Attraction.Length != 0) {
      Attraction = other.Attraction;
    }
    if (other.TransportFirm.Length != 0) {
      TransportFirm = other.TransportFirm;
    }
    if (other.NoSeats != 0) {
      NoSeats = other.NoSeats;
    }
    if (other.Price != 0) {
      Price = other.Price;
    }
    if (other.BoardingDateTime.Length != 0) {
      BoardingDateTime = other.BoardingDateTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Attraction = input.ReadString();
          break;
        }
        case 26: {
          TransportFirm = input.ReadString();
          break;
        }
        case 32: {
          NoSeats = input.ReadInt32();
          break;
        }
        case 40: {
          Price = input.ReadInt32();
          break;
        }
        case 50: {
          BoardingDateTime = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Attraction = input.ReadString();
          break;
        }
        case 26: {
          TransportFirm = input.ReadString();
          break;
        }
        case 32: {
          NoSeats = input.ReadInt32();
          break;
        }
        case 40: {
          Price = input.ReadInt32();
          break;
        }
        case 50: {
          BoardingDateTime = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ReservationDTO : pb::IMessage<ReservationDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ReservationDTO> _parser = new pb::MessageParser<ReservationDTO>(() => new ReservationDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ReservationDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoBuffsReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationDTO(ReservationDTO other) : this() {
    id_ = other.id_;
    clientName_ = other.clientName_;
    phoneNumber_ = other.phoneNumber_;
    noBookedSeats_ = other.noBookedSeats_;
    excursieId_ = other.excursieId_;
    attraction_ = other.attraction_;
    transportFirm_ = other.transportFirm_;
    noSeats_ = other.noSeats_;
    price_ = other.price_;
    boardingDateTime_ = other.boardingDateTime_;
    agencyId_ = other.agencyId_;
    name_ = other.name_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ReservationDTO Clone() {
    return new ReservationDTO(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "client_name" field.</summary>
  public const int ClientNameFieldNumber = 2;
  private string clientName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientName {
    get { return clientName_; }
    set {
      clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "phone_number" field.</summary>
  public const int PhoneNumberFieldNumber = 3;
  private string phoneNumber_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PhoneNumber {
    get { return phoneNumber_; }
    set {
      phoneNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "no_booked_seats" field.</summary>
  public const int NoBookedSeatsFieldNumber = 4;
  private int noBookedSeats_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NoBookedSeats {
    get { return noBookedSeats_; }
    set {
      noBookedSeats_ = value;
    }
  }

  /// <summary>Field number for the "excursie_id" field.</summary>
  public const int ExcursieIdFieldNumber = 5;
  private int excursieId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ExcursieId {
    get { return excursieId_; }
    set {
      excursieId_ = value;
    }
  }

  /// <summary>Field number for the "attraction" field.</summary>
  public const int AttractionFieldNumber = 6;
  private string attraction_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Attraction {
    get { return attraction_; }
    set {
      attraction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "transport_firm" field.</summary>
  public const int TransportFirmFieldNumber = 7;
  private string transportFirm_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TransportFirm {
    get { return transportFirm_; }
    set {
      transportFirm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "no_seats" field.</summary>
  public const int NoSeatsFieldNumber = 8;
  private int noSeats_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NoSeats {
    get { return noSeats_; }
    set {
      noSeats_ = value;
    }
  }

  /// <summary>Field number for the "price" field.</summary>
  public const int PriceFieldNumber = 9;
  private int price_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Price {
    get { return price_; }
    set {
      price_ = value;
    }
  }

  /// <summary>Field number for the "boarding_date_time" field.</summary>
  public const int BoardingDateTimeFieldNumber = 10;
  private string boardingDateTime_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BoardingDateTime {
    get { return boardingDateTime_; }
    set {
      boardingDateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "agency_id" field.</summary>
  public const int AgencyIdFieldNumber = 11;
  private int agencyId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AgencyId {
    get { return agencyId_; }
    set {
      agencyId_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 12;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ReservationDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ReservationDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (ClientName != other.ClientName) return false;
    if (PhoneNumber != other.PhoneNumber) return false;
    if (NoBookedSeats != other.NoBookedSeats) return false;
    if (ExcursieId != other.ExcursieId) return false;
    if (Attraction != other.Attraction) return false;
    if (TransportFirm != other.TransportFirm) return false;
    if (NoSeats != other.NoSeats) return false;
    if (Price != other.Price) return false;
    if (BoardingDateTime != other.BoardingDateTime) return false;
    if (AgencyId != other.AgencyId) return false;
    if (Name != other.Name) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
    if (PhoneNumber.Length != 0) hash ^= PhoneNumber.GetHashCode();
    if (NoBookedSeats != 0) hash ^= NoBookedSeats.GetHashCode();
    if (ExcursieId != 0) hash ^= ExcursieId.GetHashCode();
    if (Attraction.Length != 0) hash ^= Attraction.GetHashCode();
    if (TransportFirm.Length != 0) hash ^= TransportFirm.GetHashCode();
    if (NoSeats != 0) hash ^= NoSeats.GetHashCode();
    if (Price != 0) hash ^= Price.GetHashCode();
    if (BoardingDateTime.Length != 0) hash ^= BoardingDateTime.GetHashCode();
    if (AgencyId != 0) hash ^= AgencyId.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (ClientName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ClientName);
    }
    if (PhoneNumber.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(PhoneNumber);
    }
    if (NoBookedSeats != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NoBookedSeats);
    }
    if (ExcursieId != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ExcursieId);
    }
    if (Attraction.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Attraction);
    }
    if (TransportFirm.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(TransportFirm);
    }
    if (NoSeats != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(NoSeats);
    }
    if (Price != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(Price);
    }
    if (BoardingDateTime.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(BoardingDateTime);
    }
    if (AgencyId != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(AgencyId);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (ClientName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ClientName);
    }
    if (PhoneNumber.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(PhoneNumber);
    }
    if (NoBookedSeats != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(NoBookedSeats);
    }
    if (ExcursieId != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(ExcursieId);
    }
    if (Attraction.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Attraction);
    }
    if (TransportFirm.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(TransportFirm);
    }
    if (NoSeats != 0) {
      output.WriteRawTag(64);
      output.WriteInt32(NoSeats);
    }
    if (Price != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(Price);
    }
    if (BoardingDateTime.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(BoardingDateTime);
    }
    if (AgencyId != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(AgencyId);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(98);
      output.WriteString(Name);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (ClientName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
    }
    if (PhoneNumber.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneNumber);
    }
    if (NoBookedSeats != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoBookedSeats);
    }
    if (ExcursieId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExcursieId);
    }
    if (Attraction.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Attraction);
    }
    if (TransportFirm.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TransportFirm);
    }
    if (NoSeats != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoSeats);
    }
    if (Price != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
    }
    if (BoardingDateTime.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BoardingDateTime);
    }
    if (AgencyId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AgencyId);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ReservationDTO other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.ClientName.Length != 0) {
      ClientName = other.ClientName;
    }
    if (other.PhoneNumber.Length != 0) {
      PhoneNumber = other.PhoneNumber;
    }
    if (other.NoBookedSeats != 0) {
      NoBookedSeats = other.NoBookedSeats;
    }
    if (other.ExcursieId != 0) {
      ExcursieId = other.ExcursieId;
    }
    if (other.Attraction.Length != 0) {
      Attraction = other.Attraction;
    }
    if (other.TransportFirm.Length != 0) {
      TransportFirm = other.TransportFirm;
    }
    if (other.NoSeats != 0) {
      NoSeats = other.NoSeats;
    }
    if (other.Price != 0) {
      Price = other.Price;
    }
    if (other.BoardingDateTime.Length != 0) {
      BoardingDateTime = other.BoardingDateTime;
    }
    if (other.AgencyId != 0) {
      AgencyId = other.AgencyId;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          ClientName = input.ReadString();
          break;
        }
        case 26: {
          PhoneNumber = input.ReadString();
          break;
        }
        case 32: {
          NoBookedSeats = input.ReadInt32();
          break;
        }
        case 40: {
          ExcursieId = input.ReadInt32();
          break;
        }
        case 50: {
          Attraction = input.ReadString();
          break;
        }
        case 58: {
          TransportFirm = input.ReadString();
          break;
        }
        case 64: {
          NoSeats = input.ReadInt32();
          break;
        }
        case 72: {
          Price = input.ReadInt32();
          break;
        }
        case 82: {
          BoardingDateTime = input.ReadString();
          break;
        }
        case 88: {
          AgencyId = input.ReadInt32();
          break;
        }
        case 98: {
          Name = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          ClientName = input.ReadString();
          break;
        }
        case 26: {
          PhoneNumber = input.ReadString();
          break;
        }
        case 32: {
          NoBookedSeats = input.ReadInt32();
          break;
        }
        case 40: {
          ExcursieId = input.ReadInt32();
          break;
        }
        case 50: {
          Attraction = input.ReadString();
          break;
        }
        case 58: {
          TransportFirm = input.ReadString();
          break;
        }
        case 64: {
          NoSeats = input.ReadInt32();
          break;
        }
        case 72: {
          Price = input.ReadInt32();
          break;
        }
        case 82: {
          BoardingDateTime = input.ReadString();
          break;
        }
        case 88: {
          AgencyId = input.ReadInt32();
          break;
        }
        case 98: {
          Name = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoBuffsReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request(Request other) : this() {
    type_ = other.type_;
    employeeDto_ = other.employeeDto_ != null ? other.employeeDto_.Clone() : null;
    agencyDto_ = other.agencyDto_ != null ? other.agencyDto_.Clone() : null;
    reservationDto_ = other.reservationDto_ != null ? other.reservationDto_.Clone() : null;
    excursionDto_ = other.excursionDto_ != null ? other.excursionDto_.Clone() : null;
    attraction_ = other.attraction_;
    fromDate_ = other.fromDate_;
    toDate_ = other.toDate_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::RequestType type_ = global::RequestType.ReqLogin;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RequestType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "employee_dto" field.</summary>
  public const int EmployeeDtoFieldNumber = 2;
  private global::EmployeeDTO employeeDto_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EmployeeDTO EmployeeDto {
    get { return employeeDto_; }
    set {
      employeeDto_ = value;
    }
  }

  /// <summary>Field number for the "agency_dto" field.</summary>
  public const int AgencyDtoFieldNumber = 3;
  private global::AgencyDTO agencyDto_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AgencyDTO AgencyDto {
    get { return agencyDto_; }
    set {
      agencyDto_ = value;
    }
  }

  /// <summary>Field number for the "reservation_dto" field.</summary>
  public const int ReservationDtoFieldNumber = 4;
  private global::ReservationDTO reservationDto_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ReservationDTO ReservationDto {
    get { return reservationDto_; }
    set {
      reservationDto_ = value;
    }
  }

  /// <summary>Field number for the "excursion_dto" field.</summary>
  public const int ExcursionDtoFieldNumber = 5;
  private global::ExcursionDTO excursionDto_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ExcursionDTO ExcursionDto {
    get { return excursionDto_; }
    set {
      excursionDto_ = value;
    }
  }

  /// <summary>Field number for the "attraction" field.</summary>
  public const int AttractionFieldNumber = 6;
  private string attraction_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Attraction {
    get { return attraction_; }
    set {
      attraction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "from_date" field.</summary>
  public const int FromDateFieldNumber = 7;
  private string fromDate_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string FromDate {
    get { return fromDate_; }
    set {
      fromDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "to_date" field.</summary>
  public const int ToDateFieldNumber = 8;
  private string toDate_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ToDate {
    get { return toDate_; }
    set {
      toDate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(EmployeeDto, other.EmployeeDto)) return false;
    if (!object.Equals(AgencyDto, other.AgencyDto)) return false;
    if (!object.Equals(ReservationDto, other.ReservationDto)) return false;
    if (!object.Equals(ExcursionDto, other.ExcursionDto)) return false;
    if (Attraction != other.Attraction) return false;
    if (FromDate != other.FromDate) return false;
    if (ToDate != other.ToDate) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::RequestType.ReqLogin) hash ^= Type.GetHashCode();
    if (employeeDto_ != null) hash ^= EmployeeDto.GetHashCode();
    if (agencyDto_ != null) hash ^= AgencyDto.GetHashCode();
    if (reservationDto_ != null) hash ^= ReservationDto.GetHashCode();
    if (excursionDto_ != null) hash ^= ExcursionDto.GetHashCode();
    if (Attraction.Length != 0) hash ^= Attraction.GetHashCode();
    if (FromDate.Length != 0) hash ^= FromDate.GetHashCode();
    if (ToDate.Length != 0) hash ^= ToDate.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::RequestType.ReqLogin) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (employeeDto_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(EmployeeDto);
    }
    if (agencyDto_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(AgencyDto);
    }
    if (reservationDto_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(ReservationDto);
    }
    if (excursionDto_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(ExcursionDto);
    }
    if (Attraction.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Attraction);
    }
    if (FromDate.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(FromDate);
    }
    if (ToDate.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(ToDate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::RequestType.ReqLogin) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (employeeDto_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(EmployeeDto);
    }
    if (agencyDto_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(AgencyDto);
    }
    if (reservationDto_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(ReservationDto);
    }
    if (excursionDto_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(ExcursionDto);
    }
    if (Attraction.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Attraction);
    }
    if (FromDate.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(FromDate);
    }
    if (ToDate.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(ToDate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::RequestType.ReqLogin) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (employeeDto_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmployeeDto);
    }
    if (agencyDto_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AgencyDto);
    }
    if (reservationDto_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReservationDto);
    }
    if (excursionDto_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExcursionDto);
    }
    if (Attraction.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Attraction);
    }
    if (FromDate.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FromDate);
    }
    if (ToDate.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ToDate);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::RequestType.ReqLogin) {
      Type = other.Type;
    }
    if (other.employeeDto_ != null) {
      if (employeeDto_ == null) {
        EmployeeDto = new global::EmployeeDTO();
      }
      EmployeeDto.MergeFrom(other.EmployeeDto);
    }
    if (other.agencyDto_ != null) {
      if (agencyDto_ == null) {
        AgencyDto = new global::AgencyDTO();
      }
      AgencyDto.MergeFrom(other.AgencyDto);
    }
    if (other.reservationDto_ != null) {
      if (reservationDto_ == null) {
        ReservationDto = new global::ReservationDTO();
      }
      ReservationDto.MergeFrom(other.ReservationDto);
    }
    if (other.excursionDto_ != null) {
      if (excursionDto_ == null) {
        ExcursionDto = new global::ExcursionDTO();
      }
      ExcursionDto.MergeFrom(other.ExcursionDto);
    }
    if (other.Attraction.Length != 0) {
      Attraction = other.Attraction;
    }
    if (other.FromDate.Length != 0) {
      FromDate = other.FromDate;
    }
    if (other.ToDate.Length != 0) {
      ToDate = other.ToDate;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::RequestType) input.ReadEnum();
          break;
        }
        case 18: {
          if (employeeDto_ == null) {
            EmployeeDto = new global::EmployeeDTO();
          }
          input.ReadMessage(EmployeeDto);
          break;
        }
        case 26: {
          if (agencyDto_ == null) {
            AgencyDto = new global::AgencyDTO();
          }
          input.ReadMessage(AgencyDto);
          break;
        }
        case 34: {
          if (reservationDto_ == null) {
            ReservationDto = new global::ReservationDTO();
          }
          input.ReadMessage(ReservationDto);
          break;
        }
        case 42: {
          if (excursionDto_ == null) {
            ExcursionDto = new global::ExcursionDTO();
          }
          input.ReadMessage(ExcursionDto);
          break;
        }
        case 50: {
          Attraction = input.ReadString();
          break;
        }
        case 58: {
          FromDate = input.ReadString();
          break;
        }
        case 66: {
          ToDate = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::RequestType) input.ReadEnum();
          break;
        }
        case 18: {
          if (employeeDto_ == null) {
            EmployeeDto = new global::EmployeeDTO();
          }
          input.ReadMessage(EmployeeDto);
          break;
        }
        case 26: {
          if (agencyDto_ == null) {
            AgencyDto = new global::AgencyDTO();
          }
          input.ReadMessage(AgencyDto);
          break;
        }
        case 34: {
          if (reservationDto_ == null) {
            ReservationDto = new global::ReservationDTO();
          }
          input.ReadMessage(ReservationDto);
          break;
        }
        case 42: {
          if (excursionDto_ == null) {
            ExcursionDto = new global::ExcursionDTO();
          }
          input.ReadMessage(ExcursionDto);
          break;
        }
        case 50: {
          Attraction = input.ReadString();
          break;
        }
        case 58: {
          FromDate = input.ReadString();
          break;
        }
        case 66: {
          ToDate = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoBuffsReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response(Response other) : this() {
    type_ = other.type_;
    employeeDto_ = other.employeeDto_ != null ? other.employeeDto_.Clone() : null;
    errorMessage_ = other.errorMessage_;
    excursionDto_ = other.excursionDto_.Clone();
    reservationDto_ = other.reservationDto_.Clone();
    noRemainingSeats_ = other.noRemainingSeats_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::ResponseType type_ = global::ResponseType.RespLogin;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ResponseType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "employee_dto" field.</summary>
  public const int EmployeeDtoFieldNumber = 2;
  private global::EmployeeDTO employeeDto_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EmployeeDTO EmployeeDto {
    get { return employeeDto_; }
    set {
      employeeDto_ = value;
    }
  }

  /// <summary>Field number for the "error_message" field.</summary>
  public const int ErrorMessageFieldNumber = 3;
  private string errorMessage_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ErrorMessage {
    get { return errorMessage_; }
    set {
      errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "excursion_dto" field.</summary>
  public const int ExcursionDtoFieldNumber = 4;
  private static readonly pb::FieldCodec<global::ExcursionDTO> _repeated_excursionDto_codec
      = pb::FieldCodec.ForMessage(34, global::ExcursionDTO.Parser);
  private readonly pbc::RepeatedField<global::ExcursionDTO> excursionDto_ = new pbc::RepeatedField<global::ExcursionDTO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ExcursionDTO> ExcursionDto {
    get { return excursionDto_; }
  }

  /// <summary>Field number for the "reservation_dto" field.</summary>
  public const int ReservationDtoFieldNumber = 5;
  private static readonly pb::FieldCodec<global::ReservationDTO> _repeated_reservationDto_codec
      = pb::FieldCodec.ForMessage(42, global::ReservationDTO.Parser);
  private readonly pbc::RepeatedField<global::ReservationDTO> reservationDto_ = new pbc::RepeatedField<global::ReservationDTO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ReservationDTO> ReservationDto {
    get { return reservationDto_; }
  }

  /// <summary>Field number for the "no_remaining_seats" field.</summary>
  public const int NoRemainingSeatsFieldNumber = 6;
  private int noRemainingSeats_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NoRemainingSeats {
    get { return noRemainingSeats_; }
    set {
      noRemainingSeats_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(EmployeeDto, other.EmployeeDto)) return false;
    if (ErrorMessage != other.ErrorMessage) return false;
    if(!excursionDto_.Equals(other.excursionDto_)) return false;
    if(!reservationDto_.Equals(other.reservationDto_)) return false;
    if (NoRemainingSeats != other.NoRemainingSeats) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::ResponseType.RespLogin) hash ^= Type.GetHashCode();
    if (employeeDto_ != null) hash ^= EmployeeDto.GetHashCode();
    if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
    hash ^= excursionDto_.GetHashCode();
    hash ^= reservationDto_.GetHashCode();
    if (NoRemainingSeats != 0) hash ^= NoRemainingSeats.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::ResponseType.RespLogin) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (employeeDto_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(EmployeeDto);
    }
    if (ErrorMessage.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ErrorMessage);
    }
    excursionDto_.WriteTo(output, _repeated_excursionDto_codec);
    reservationDto_.WriteTo(output, _repeated_reservationDto_codec);
    if (NoRemainingSeats != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(NoRemainingSeats);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::ResponseType.RespLogin) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (employeeDto_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(EmployeeDto);
    }
    if (ErrorMessage.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(ErrorMessage);
    }
    excursionDto_.WriteTo(ref output, _repeated_excursionDto_codec);
    reservationDto_.WriteTo(ref output, _repeated_reservationDto_codec);
    if (NoRemainingSeats != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(NoRemainingSeats);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::ResponseType.RespLogin) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (employeeDto_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmployeeDto);
    }
    if (ErrorMessage.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
    }
    size += excursionDto_.CalculateSize(_repeated_excursionDto_codec);
    size += reservationDto_.CalculateSize(_repeated_reservationDto_codec);
    if (NoRemainingSeats != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoRemainingSeats);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::ResponseType.RespLogin) {
      Type = other.Type;
    }
    if (other.employeeDto_ != null) {
      if (employeeDto_ == null) {
        EmployeeDto = new global::EmployeeDTO();
      }
      EmployeeDto.MergeFrom(other.EmployeeDto);
    }
    if (other.ErrorMessage.Length != 0) {
      ErrorMessage = other.ErrorMessage;
    }
    excursionDto_.Add(other.excursionDto_);
    reservationDto_.Add(other.reservationDto_);
    if (other.NoRemainingSeats != 0) {
      NoRemainingSeats = other.NoRemainingSeats;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::ResponseType) input.ReadEnum();
          break;
        }
        case 18: {
          if (employeeDto_ == null) {
            EmployeeDto = new global::EmployeeDTO();
          }
          input.ReadMessage(EmployeeDto);
          break;
        }
        case 26: {
          ErrorMessage = input.ReadString();
          break;
        }
        case 34: {
          excursionDto_.AddEntriesFrom(input, _repeated_excursionDto_codec);
          break;
        }
        case 42: {
          reservationDto_.AddEntriesFrom(input, _repeated_reservationDto_codec);
          break;
        }
        case 48: {
          NoRemainingSeats = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::ResponseType) input.ReadEnum();
          break;
        }
        case 18: {
          if (employeeDto_ == null) {
            EmployeeDto = new global::EmployeeDTO();
          }
          input.ReadMessage(EmployeeDto);
          break;
        }
        case 26: {
          ErrorMessage = input.ReadString();
          break;
        }
        case 34: {
          excursionDto_.AddEntriesFrom(ref input, _repeated_excursionDto_codec);
          break;
        }
        case 42: {
          reservationDto_.AddEntriesFrom(ref input, _repeated_reservationDto_codec);
          break;
        }
        case 48: {
          NoRemainingSeats = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
