CREATE DATABASE Facultateea
GO
USE Facultateea
GO

CREATE TABLE Versiune(
Vid INT PRIMARY PRIMARY KEY IDENTITY,
NrV INT DEFAULT 0
)

CREATE TABLE Orar(
Oid INT PRIMARY KEY IDENTITY,
Descrierre VARCHAR(50),
)


CREATE TABLE Cursuri(
Cid INT PRIMARY KEY IDENTITY,
Denumire VARCHAR(50),
Descriere VARCHAR(50),
Oid INT FOREIGN KEY REFERENCES Orar(Oid)
)

CREATE TABLE SaliDeClasa(
Scid INT PRIMARY KEY IDENTITY,
Denumire VARCHAR(50),
Descriere VARCHAR(50),
Cid INT FOREIGN KEY REFERENCES Cursuri(Cid)
)



CREATE TABLE Facultate(
Fid INT PRIMARY KEY IDENTITY,
Denumire VARCHAR(50),
)
CREATE TABLE Profesori(
Pid INT PRIMARY KEY IDENTITY,
Nume VARCHAR(50),
Prenume VARCHAR(50),
Studii VARCHAR(50)
)
CREATE TABLE DepartamentProfesori(
Did INT FOREIGN KEY REFERENCES Profesori(Pid),
Denumire VARCHAR(50),
Constraint pk_DepartamentProfesori PRIMARY KEY(Did)
)
CREATE TABLE Specializare(
SPid INT PRIMARY KEY IDENTITY,
Denumire VARCHAR(50),
Fid INT FOREIGN KEY REFERENCES Facultate(Fid),
Did INT FOREIGN KEY REFERENCES DepartamentProfesori(Did)
)

CREATE TABLE Grupe(
Gid INT FOREIGN KEY REFERENCES Orar(Oid),
Denumire VARCHAR(50),
Spid INT FOREIGN KEY REFERENCES Specializare(SPid),
CONSTRAINT pk_Grupe PRIMARY KEY(Gid)
)

CREATE TABLE Studenti(
Sid INT PRIMARY KEY IDENTITY,
Nume VARCHAR(50),
Prenume VARCHAR(50),
Media  INT NOT NULL,
Gid INT FOREIGN KEY REFERENCES Grupe(Gid),
)

CREATE TABLE SefDeGrupa(
Sfid INT FOREIGN KEY REFERENCES Studenti(Sid),
CONSTRAINT pk_SefDeGrupa PRIMARY KEY (Sfid)
)



